openapi: 3.0.0
tags:
  - name: endpoint
  - name: apimodel
  - name: schema
info:
  title: ApiModel
  version: '1.0'
  description: Api model for front and backend
  contact:
    name: Tiago Rodrigues Cunha
    email: tiago.r.c.sn@gmail.com
  license:
    name: MIT
servers:
  - url: 'http://localhost:5000'
paths:
  '/users/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: GetUserById
      tags:
        - endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./User.v1.yaml
              examples:
                example-1:
                  value:
                    id: 8cac0d4f-dc0d-442d-95f3-5741c8843993
                    name: Tiago
                    password: '123456'
                    tag: tiago-tag-12345
                    email: tiago@example.com
                    character:
                      firstname: Oliver
                      lastname: Cromwell
                      grade: trainer
                      experience: 999999999
                      image: ''
                      status:
                        id: 73ee962c-18b8-4fe1-8187-7b444a139432
                      skills: {}
                      equipaments:
                        head:
                          id: 082c70f5-76ae-4374-8a2b-12794c2e401f
                          image: ''
                          durability: 9999999
                          defence: 9999999
                          price: 9999999
                          name: Capacete
                          description: Pra proteger a cabeça
                          fragmentSlot: 1
                          tag: capacete-tag-1234
                        body:
                          id: 03c8904b-65c8-461c-aadc-15aa18cde565
                          image: ''
                          durability: 9999999
                          defence: 9999999
                          price: 9999999
                          name: Colete
                          description: Pra proteger o torço
                          fragmentSlot: 1
                          tag: colete-tag-1234
                        hands:
                          id: af435562-30dc-4341-9fa0-e3b7edfbc767
                          image: ''
                          durability: 9999999
                          defence: 9999999
                          price: 9999999
                          name: Luvas
                          description: Pra proteger as mãos
                          fragmentSlot: 1
                          tag: luvas-tag-1234
                        legs:
                          id: d3364080-cb3e-455c-bc3a-b7f178710f62
                          image: ''
                          durability: 9999999
                          defence: 9999999
                          price: 9999999
                          name: Calças
                          description: Pra proteger as pernas
                          fragmentSlot: 1
                          tag: calcas-tag-1234
                        feet:
                          id: 3affe0e2-38a8-4901-9cbd-dd9c499cdc4f
                          image: ''
                          durability: 9999999
                          defence: 9999999
                          price: 9999999
                          name: botas
                          description: Pra proteger os pés
                          fragmentSlot: 1
                          tag: botas-tag-1234
                        neck:
                          id: a16a5206-0ba8-473a-ac3b-8f1e130bc16f
                          image: ''
                          durability: 9999999
                          defence: 9999999
                          price: 9999999
                          name: Cordão
                          description: Pra dar sorte
                          fragmentSlot: 1
                          tag: Cordão-tag-1234
                        primaryWeapon:
                          id: 2c3b7ec6-fbdb-45dd-86f4-4e8152b2330c
                          image: ''
                          durability: 9999999
                          defence: 9999999
                          attack: 9999999
                          price: 9999999
                          name: espada
                          description: Pra atacar
                          fragmentSlot: 1
                          tag: espada-tag-1234
                          twoHanded: false
                          needArmmo: false
                        secondWeapon:
                          id: 56baf84a-b5cc-42ae-a1dc-b68cdf673a9f
                          image: ''
                          durability: 9999999
                          defence: 9999999
                          attack: 0
                          price: 9999999
                          name: escudo
                          description: 'Embora está na aba arma, não é pra bater'
                          fragmentSlot: 1
                          tag: escudo-tag-1234
                          twoHanded: false
                          needArmmo: false
                        armmo: {}
                        belt:
                          id: e119fb58-83d0-47dd-bc6e-c8af691cc994
                          image: ''
                          durability: 9999999
                          defence: 9999999
                          price: 9999999
                          name: Cinto
                          description: Pra segurar as calças e carregar porções
                          fragmentSlot: 1
                          tag: Cinto-tag-1234
                      potions: {}
                      defence: 99999999
                      attack: 99999999
                      power: 99999999
                      stamina: 99999999
                      id: 9671b6bf-a3ab-40f1-8b06-dd27a2179686
                    points: 99999
          headers: {}
        '404':
          description: Created
      operationId: get-users-id
      parameters:
        - schema:
            type: string
          in: query
          name: id
      description: Get one user by id
components:
  schemas:
    User:
      $ref: ./User.v1.yaml
