/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

export interface components {
  schemas: {
    /**
     * User schema
     */
    User: {
      id: string;
      name: string;
      password: string;
      tag: string;
      email: string;
      character: {
        firstname: string;
        lastname: string;
        grade: string;
        experience: number;
        image: string;
        status: { id: string };
        skills: { [key: string]: any };
        equipaments: {
          head?: {
            id?: string;
            image: string;
            durability: number;
            defence: number;
            price: number;
            name: string;
            description: string;
            fragmentSlot: number;
            tag: string;
          };
          body?: {
            id: string;
            image: string;
            durability: number;
            defence: number;
            price: number;
            name: string;
            description: string;
            fragmentSlot: number;
            tag: string;
          };
          hands?: {
            id: string;
            image: string;
            durability: number;
            defence: number;
            price: number;
            name: string;
            description: string;
            fragmentSlot: number;
            tag: string;
          };
          legs?: {
            id: string;
            image: string;
            durability: number;
            defence: number;
            price: number;
            name: string;
            description: string;
            fragmentSlot: number;
            tag: string;
          };
          feet?: {
            id: string;
            image: string;
            durability: number;
            defence: number;
            price: number;
            name: string;
            description: string;
            fragmentSlot: number;
            tag: string;
          };
          neck?: {
            id: string;
            image: string;
            durability: number;
            defence: number;
            price: number;
            name: string;
            description: string;
            fragmentSlot: number;
            tag: string;
          };
          primaryWeapon?: {
            id: string;
            image: string;
            durability: number;
            defence: number;
            attack: number;
            price: number;
            name: string;
            description: string;
            fragmentSlot: number;
            tag: string;
            twoHanded: boolean;
            needArmmo: boolean;
          };
          secondWeapon?: {
            id: string;
            image: string;
            durability: number;
            defence: number;
            attack: number;
            price: number;
            name: string;
            description: string;
            fragmentSlot: number;
            tag: string;
            twoHanded: boolean;
            needArmmo: boolean;
          };
          armmo?: { id: string };
          belt?: {
            id: string;
            image: string;
            durability: number;
            defence: number;
            price: number;
            name: string;
            description: string;
            fragmentSlot: number;
            tag: string;
          };
        };
        potions?: { id: string };
        defence: number;
        attack: number;
        power: number;
        stamina: number;
        id: string;
      };
      points: number;
    };
  };
}
