version: '3'

services:
  api:
    image: api
    build:
      context: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:5000"
      - "5001:80"
    